<template>
  <div>
    <div v-if="loading" class="flex justify-center my-8">
      <div class="animate-spin rounded-full h-10 w-10 border-b-2 border-black"></div>
    </div>

    <div v-else-if="error" class="bg-red-50 p-4 rounded-lg my-4">
      <p class="text-red-700">{{ error }}</p>
    </div>

    <div v-else class="bg-white rounded-lg shadow p-6 my-4">
      <div class="flex justify-between items-center mb-4">
        <h3 class="text-lg font-semibold">AI Overview</h3>
      </div>

      <div v-if="!results" class="border border-gray-200 rounded-lg p-4 bg-gray-50">
        <p class="text-gray-500 text-center">
          Click "Get AI Overview" to understand what this search is about.
        </p>
      </div>

      <div v-else class="border border-gray-200 rounded-lg p-4 bg-gray-50">
        <div class="mb-4">
          <div class="flex justify-between text-xs text-gray-500 mb-2">
            <span>Generated by: Qwen 0.5B</span>
            <span v-if="results.token_usage">
              Tokens: {{ results.token_usage.total_tokens }}
            </span>
          </div>
          <div class="text-gray-800 prose prose-sm max-w-none">
            <p v-for="(paragraph, i) in formattedResponse" :key="i" class="mb-2">
              {{ paragraph }}
            </p>
          </div>
        </div>
      </div>

      <div class="mt-4 flex justify-end">
        <button 
          @click="getOverview" 
          class="px-4 py-2 bg-black text-white rounded-full hover:bg-gray-800 flex items-center"
          :disabled="isAnalyzing"
        >
          <span v-if="isAnalyzing" class="mr-2 animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full"></span>
          {{ isAnalyzing ? 'Generating...' : 'Get AI Overview' }}
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'

const props = defineProps({
  query: {
    type: String,
    required: true
  },
  documents: {
    type: Array,
    required: true
  }
})

const loading = ref(false)
const error = ref(null)
const results = ref(null)
const isAnalyzing = ref(false)

// Format response with paragraphs
const formattedResponse = computed(() => {
  if (!results.value || !results.value.response) return []
  return results.value.response.split('\n\n').filter(p => p.trim() !== '')
})

// Function to get overview with LLM
async function getOverview() {
  if (isAnalyzing.value || !props.query || props.documents.length === 0) return
  
  isAnalyzing.value = true
  error.value = null
  
  try {
    const config = useRuntimeConfig()
    console.log(props.documents)
    const response = await fetch(`${config.public.NUXT_PUBLIC_API_URL}/llm/analyze`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        query: props.query,
        documents: props.documents,
        temperature: 0.3,
        max_tokens: 500
      })
    })
    
    if (!response.ok) {
      throw new Error(`Error: ${response.status} - ${await response.text()}`)
    }
    
    results.value = await response.json()
  } catch (err) {
    console.error('LLM overview error:', err)
    error.value = `Failed to generate overview: ${err.message}`
  } finally {
    isAnalyzing.value = false
  }
}
</script>
